### ISSUE TITLE
아니면 CSS대신 SASS를 쓰자 (SASS 문법 10분 총정리)

### ISSUE THREAD

**Issue by Yeonlisa** [Yeonlisa/Shop#9]
# SASS란?

> CSS를 변수, 반복문, 함수 같은 문법으로 다룰 수 있는 전처리기
> 

# SASS 사용을 위한 node-sass 설치

터미널 키고

```jsx
npm install node-sass
```

# SASS 사용을 위한 node-sass 셋팅

파일명을 `.scss` 로 해주고 원하는 파일에 import 해주면 CSS 파일로 자동으로 알아서 컴파일해준다.

```scss
(Detail.scss 파일)

.red {
  color : red;
}
```

```jsx
(Detail.js 파일)

import './Detail.scss';
```

# SASS 문법

## 1. 변수 사용

```scss
(Detail.scss)

$메인칼라 : #ff0000;

.red {
  color : $메인칼라;
}
```

`$변수명` : 집어넣을값;

이렇게 변수를 만들고 원하는 곳에서 사용가능하다.

색상 분만 아니라 px, % 값 등 여러가지를 넣을 수 있고, 변수명은 한글도 가능하다.

## 2. @import

CSS 파일간 import를 할 수 있는 문법이다.

```scss
@import './어쩌구.css';
```

CSS 파일을 작성하다보면 자주 사용하는 스타일들이 간혹 있는데 reset 이라고 보통 부른다.

```css
body {
  margin : 0;
} 
div {
  box-sizing : border-box;
}
```

이런 것을 다른 css(혹은 scss)파일에 저장해두고 필요할때마다 `@import` 해오면 편리하다.

## 3. nesting

CSS를 작성하다보면 셀렉터를 길고 복잡하게 알아보기 힘들게 쓰는 경우가 있다.

```css
div.container h4 {
  color : blue;
}
div.container p {
  color : green;
}
```

그러나 SCSS 파일 안에선 셀렉터 말고 이렇게 개발이 가능하다.

```scss
div.container {
  h4 {
    color : blue;
  }
  p {
    color : green;
  }
}
```

`nesting` : 셀렉터를 옆으로 길게 나열하는게 아니라 안쪽에 작성하는 것

사용 이유 : 셀렉터 해석이 쉽고 관련된 class끼리 한 덩어리로 관리하기 편하기 때문이다.

# 4. extend

알림창 예시)

```scss
(Detail.scss 파일)

.my-alert {
  background : #eeeeee;
  padding : 15px;
  border-radius : 5px;
  max-width : 500px;
  width : 100%;
  margin : auto;
}
.my-alert p {
  margin-bottom : 0;
}
```

```jsx
(Detail.js 파일)

function Detail(){
  return (
    <div>
      <HTML많은곳/>
      <div className="my-alert">
        <p>재고가 얼마 남지 않았습니다</p>
      </div>
    </div>
  )
}
```

이렇게 있을때 다양한 배경색의 알림창이 또 필요해지면 손수 복붙하지않고 `@extend` 문법을 사용한다.

```scss
(Detail.scss 파일)

.my-alert {
  background : #eeeeee;
  padding : 15px;
  border-radius : 5px;
  max-width : 500px;
  width : 100%;
  margin : auto;
}
.my-alert2 {
  @extend .my-alert;
  background : yellow;
}

.my-alert p {
  margin-bottom : 0;
}
```

`@extend 클래스명` : 클래스명에 들어있는 모든 내용을 그 자리에 복붙해준다.

→ CSS코드를 재사용할 일이 있을때 손수 복붙하지 않아도 되고 비슷한 UI 만들기도 쉬워진다.

# 5. @ mixin / @ include

`@mixin 함수명()` : 함수만드는 문법(코드 축약하고 재사용할 때 많이씀)으로 SASS에서는 function 키워드 대신에 **@mixin** 이라고 쓰고 중괄호 안에 축약하고 싶은 코드들을 담는다.

`@include 함수명()` : 함수를 부를때 사용한다.

```scss
(Detail.scss 파일)

@mixin 함수() {
  background : #eeeeee;
  padding : 15px;
  border-radius : 5px;
  max-width : 500px;
  width : 100%;
  margin : auto;
}
.my-alert {
  @include 함수()
}

.my-alert p {
  margin-bottom : 0;
}
```
